# Q1.importing necessary pages:


In [242]:
import numpy as np
import pandas as pd


In [243]:
#Q1. Pandas version

pd.__version__

'1.5.3'

In [244]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv'

In [245]:
df = pd.read_csv(data)  

# Q2. Records count


In [247]:
#How many records are in the dataset? 2160 
df

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

# Q3. Laptop brands 

In [248]:
#How many laptop brands are presented in the dataset? 2160
df['Laptop']

0       ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...
1       Alurin Go Start Intel Celeron N4020/8GB/256GB ...
2       ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...
3       MSI Katana GF66 12UC-082XES Intel Core i7-1270...
4       HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...
                              ...                        
2155    Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...
2156    Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...
2157    Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...
2158    Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...
2159    Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...
Name: Laptop, Length: 2160, dtype: object

In [249]:
df.index

RangeIndex(start=0, stop=2160, step=1)

# Q4. Missing values

In [250]:
# How many columns in the dataset have missing values? 3 columns
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [251]:
df.describe()


RAM      Storage       Screen  Final Price
count  2160.000000  2160.000000  2156.000000  2160.000000
mean     15.413889   596.294444    15.168112  1312.638509
std       9.867815   361.220506     1.203329   911.475417
min       4.000000     0.000000    10.100000   201.050000
25%       8.000000   256.000000    14.000000   661.082500
50%      16.000000   512.000000    15.600000  1031.945000
75%      16.000000  1000.000000    15.600000  1708.970000
max     128.000000  4000.000000    18.000000  7150.470000

In [254]:
df.nunique()

Laptop          2160
Status             2
Brand             27
Model            121
CPU               28
RAM                9
Storage           12
Storage type       2
GPU               44
Screen            29
Touch              2
Final Price     1440
dtype: int64

In [255]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

# Q5. Maximum final price

In [175]:
# What's the maximum final price of Dell notebooks in the dataset? 3936
df_Dell['Final Price'].max()

3936.0

In [142]:
df_max = df_Dell[df_Dell['Final Price']== df_Dell['Final Price'].max()]

In [143]:
print(df_max)

                                                 Laptop Status Brand  \
1335  Dell Precision 5770 Intel Core i7-12700H/16GB/...    New  Dell   

          Model            CPU  RAM  Storage Storage type        GPU  Screen  \
1335  Precision  Intel Core i7   16      512          SSD  RTX A2000    17.0   

     Touch  Final Price  
1335   Yes       3936.0  


In [260]:
df_Dell=df[df['Brand']=='Dell']

df_Dell

Laptop       Status Brand  \
161   Dell Vostro 3510 Intel Core i3-1115G4/8 GB/256...          New  Dell   
271   Dell Vostro 3510 Intel Core i5-1135G7/8 GB/256...          New  Dell   
281   Dell Vostro 3520 Intel Core i7-1255U/16GB/512G...          New  Dell   
319   Dell Latitude 3520 Intel Core i5-1135G7/8GB/25...          New  Dell   
328   Dell Vostro 3510 Intel Core i5-1135G7/16 GB/51...          New  Dell   
...                                                 ...          ...   ...   
1843  Dell Vostro 5301 Intel Core i5-1135G7/8GB/256G...  Refurbished  Dell   
1844  Dell Vostro 5301 Intel Core i5-1135G7/8GB/512G...  Refurbished  Dell   
1845  Dell Vostro 5502 Intel Core i5-1135G7/8GB/512G...  Refurbished  Dell   
1846  Dell XPS 13 9300 Intel Core i5-1035G1/8GB/512G...  Refurbished  Dell   
1847  Dell XPS 7390 Intel Core i7-10510U/16GB/512GB ...  Refurbished  Dell   

         Model            CPU  RAM  Storage Storage type  GPU  Screen Touch  \
161     Vostro  Intel Core i3    8      256          SSD  NaN    15.6    No   
271     Vostro  Intel Core i5    8      256          SSD  NaN    15.6    No   
281     Vostro  Intel Core i7   16      512          SSD  NaN    15.6    No   
319   Latitude  Intel Core i5    8      256          SSD  NaN    15.6    No   
328     Vostro  Intel Core i5   16      512          SSD  NaN    15.6    No   
...        ...            ...  ...      ...          ...  ...     ...   ...   
1843    Vostro  Intel Core i5    8      256          SSD  NaN    13.3    No   
1844    Vostro  Intel Core i5    8      512          SSD  NaN    13.3    No   
1845    Vostro  Intel Core i5    8      512          SSD  NaN    15.6    No   
1846       XPS  Intel Core i5    8      512          SSD  NaN    13.4    No   
1847       XPS  Intel Core i7   16      512          SSD  NaN    13.3    No   

      Final Price  
161        599.00  
271        690.15  
281        889.00  
319        789.00  
328        869.00  
...           ...  
1843       420.74  
1844       511.59  
1845       549.93  
1846       699.00  
1847      1086.88  

[84 rows x 12 columns]

# Q6. Median value of Screen

In [144]:
# 1.Find the median value of Screen column in the dataset.
df.Screen.median()

15.6

In [145]:
df.Screen.describe()

count    2156.000000
mean       15.168112
std         1.203329
min        10.100000
25%        14.000000
50%        15.600000
75%        15.600000
max        18.000000
Name: Screen, dtype: float64

In [149]:
# 2. Next, calculate the most frequent value of the same Screen column.

df.Screen.mode()

0    15.6
Name: Screen, dtype: float64

In [ ]:
# 3. Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.


In [150]:
df.Screen.replace(' ', '15.6')

0       15.6
1       15.6
2       15.6
3       15.6
4       15.6
        ... 
2155    17.3
2156    17.3
2157    17.3
2158    13.4
2159    13.4
Name: Screen, Length: 2160, dtype: float64

In [151]:
# 4. Now, calculate the median value of Screen once again.

df.Screen.median()

15.6

In [152]:
# Hint: refer to existing mode and median functions to complete the task.
No,It is the same value.

NameError: name 'No' is not defined

# Q7. Sum of weights

In [153]:
# 1. Select all the "Innjoo" laptops from the dataset.
df_Innjoo=df[df['Brand']=='Innjoo']

In [154]:
df_Innjoo

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [163]:
# 2. Select only columns RAM, Storage, Screen.
df_Innjoo[['RAM','Storage','Screen']]

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [196]:
# 3. Get the underlying NumPy array. Let's call
x = df_Innjoo[['RAM','Storage','Screen']]
x

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [197]:
x.values

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [ ]:
# 4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [198]:
x.values.shape

(6, 3)

In [203]:
x = x.values

In [208]:
x = np.array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])


In [209]:
# calculate the transpose of x
x_T = x.T
xTx = np.matmul(x_T,x)

print (xTx)

[[2.52000e+02 8.32000e+03 5.59800e+02]
 [8.32000e+03 3.68640e+05 1.73952e+04]
 [5.59800e+02 1.73952e+04 1.28196e+03]]


In [210]:
# 5. Compute the inverse of XTX.

xTx_inv = np.linalg.inv(xTx)

print(xTx_inv)

[[ 2.78025381e-01 -1.51791334e-03 -1.00809855e-01]
 [-1.51791334e-03  1.58286725e-05  4.48052175e-04]
 [-1.00809855e-01  4.48052175e-04  3.87214888e-02]]


In [211]:
# 6. Create an array y with values [1100, 1300, 800, 900, 1000, 1100].

y = [1100, 1300, 800, 900, 1000, 1100]

In [215]:
# 7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
#w = ((xTx,xTx_inv),y)
w = np.linalg.solve(xTx, np.matmul(x.T, y))


In [213]:
w

((array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
         [8.32000e+03, 3.68640e+05, 1.73952e+04],
         [5.59800e+02, 1.73952e+04, 1.28196e+03]]),
  array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
         [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
         [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])),
 [1100, 1300, 800, 900, 1000, 1100])

In [218]:
# 8. What's the sum of all the elements of the result?


w.sum()

91.29988062995699